name: OSRT ManyLinux CI

on: [push, pull_request]



jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
          fail-fast: false
          matrix:
            os: [ubuntu-22.04]
            python-minor-version: [9, 10, 11, 12]

        steps:
          # Checkout the repo
          - name: Checkout the repo
            uses: actions/checkout@v3
          # Install Python 3.9+
          - name: Install required development tools - Python 3.${{ matrix.python-minor-version }}
            uses: actions/setup-python@v4
            with:
                python-version: '3.${{ matrix.python-minor-version }}'
          - name: Verify the Python version
            run: |
                python3 -c "import sys; exit(not (sys.version_info.major == 3 and sys.version_info.minor == ${{ matrix.python-minor-version }}))"
          
          
          
          
          - name: Build the wheel with Docker
            uses: addnab/docker-run-action@v3
            with:
                image: quay.io/pypa/manylinux2014_x86_64
                options: -v ${{ github.workspace }}:/source
                run: |
                    yum install -y zip
                    yum install -y cmake
                    yum install -y ninja-build
                    yum install -y pkgconfig
                    python3.${{ matrix.python-minor-version }} -m pip install --upgrade scikit-build
                    python3.${{ matrix.python-minor-version }} -m pip install --upgrade auditwheel
                    yum install -y patchelf
                    git clone https://github.com/Microsoft/vcpkg.git
                    ./vcpkg/bootstrap-vcpkg.sh
                    export PATH=/vcpkg:$PATH
                    export VCPKG_INSTALLATION_ROOT=/vcpkg
                    vcpkg install tbb
                    vcpkg install gmp
                    cd /source
                    python3.${{ matrix.python-minor-version }} build.py
            
          # Run the sample experiment
          - name: Install the OSRT Python module and run the sample experiment (Python 3.9 - 3.11)
            if: matrix.python-minor-version != 12
            run: |
                python3 -c "import sys; exit(not (sys.version_info.major == 3 and sys.version_info.minor == ${{ matrix.python-minor-version }}))"
                pip3 install attrs packaging editables pandas scikit-learn sortedcontainers gmpy2 matplotlib
                python3 -c "import os; import subprocess; exit(subprocess.run(['pip3', 'install', 'dist/{}'.format(os.listdir('dist')[0])]).returncode)"
                python3 osrt/example.py
          - name: Install the OSRT Python module and run the sample experiment (Python 3.12)
            if: matrix.python-minor-version == 12
            run: |
                python3 -c "import sys; exit(not (sys.version_info.major == 3 and sys.version_info.minor == ${{ matrix.python-minor-version }}))"
                pip3 install attrs packaging editables pandas scikit-learn sortedcontainers gmpy2==2.2.0a1 matplotlib
                python3 -c "import os; import subprocess; exit(subprocess.run(['pip3', 'install', 'dist/{}'.format(os.listdir('dist')[0])]).returncode)"
                python3 osrt/example.py
          